config/routes.rb
Musicbox::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :musics
  resources :users

  root  'static_pages#index'
   
  match '/signin',               to:  'sessions#login' ,          via: 'get'
  match '/signout',              to:  'sessions#destroy',         via: 'delete'
  match '/signup',               to:  'users#register' ,          via: 'get'
  match '/contactus',            to:  'static_pages#contactus',   via: 'get'
  
  
  get 'select' => 'musics#select'
  get 'show' => 'music#show'
  get 'search' => 'static_pages#search'
  get 'stats/:id' => 'musics#stats'

end

app/models/music.rb
class Music < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]

  # GET /musics
  # GET /musics.json
  def select

    if params[:Theme] == "all"
      @musics = Music.all
      @status = "These are all the 1000 songs you should listen before you die!"
    else
      @musics = Music.where("Theme like ?", "%#{params[:Theme]}")
      @status = "#{@musics.size} songs found for this Theme"
    end
   @musics = @musics.order("Theme ASC")
   render :layout => 'select'
 end

  #def index
   # @musics = Music.all
  #end

  # GET /musics/1
  # GET /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render action: 'show', status: :created, location: @music }
      else
        format.html { render action: 'new' }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:Theme, :Title, :Artist, :Year, :Spotify_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def Home
  end

  def Sign_in
  end

  def signup
  end

  def Contact_us
  end

  def search
    @musics = Music.where("lower(name) like ?", "%#{params[:query].downcase}%")
    @status = "No result found"
    @musics = @musics.order("name ASC")
    render :layout => 'select'
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<%= link_to "Musicbox", root_path%> 
<ul>
   <li><%= link_to "Home", root_path %></li>
   <% if signed_in? %>
   <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
   <% else %>
    <li><%= link_to "Sign in", signin_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicbox | <%= yield(:title) %></title>
  <%= stylesheet_link_tag "grid" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<script>
  function loadsearch()
  {
  var xmlhttp;
  if (window.XMLHttpRequest)
    {// code for IE7+, Firefox, Chrome, Opera, Safari
    xmlhttp=new XMLHttpRequest();
    }
  else
    {// code for IE6, IE5
    xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
  xmlhttp.onreadystatechange=function()
    {
    if (xmlhttp.readyState==4 && xmlhttp.status==200)
      {
      document.getElementById('searchresult').style.display = "block";
      document.getElementById("searchresult").innerHTML=xmlhttp.responseText;
      }
    if (str == "")
    {
      document.getElementById('searchresult').style.display = "none";
    }
    }
    
  var str = document.getElementById("searchbox").value;
  xmlhttp.open("GET","../search.html?query="+str,true);
  xmlhttp.send();

  }
  </script>
</head>

<body class="container_12">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=155786951179530";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	<div class="navbar grid_12">
		<div class="navitem"><a href="/">Home</a></div>
    
    
    
  <div class="pathbar">
	<%if @Music != nil %>
		<div class='pathitem'><a href="/musics/<%= @Music.id %>"><%= @Music.Theme %></a></div>
	<%end%>
	<%if @stats == true %>
		<div class="pathitem">></div>
		<div class='pathitem'>Stats</div>
	<%end%>
</div>
<div class="grid_12">
  <%= yield %>
</div> 
   <div class="container">
     <% flash.each do |key, value| %>
       <div class="alert alert-<%= key %>"><%= value %></div>
     <% end %>
   </div>
  
</div>
</body>
</html>

app/views/layouts/select.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicBox</title>
  <%= stylesheet_link_tag "grid" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container_12">

<%= yield %>

</body>
</html>

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Theme %><br>
    <%= f.text_field :Theme %>
  </div>
  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :Artist %><br>
    <%= f.text_field :Artist %>
  </div>
  <div class="field">
    <%= f.label :Year %><br>
    <%= f.number_field :Year %>
  </div>
  <div class="field">
    <%= f.label :Spotify_url %><br>
    <%= f.text_field :Spotify_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<h1>Listing musics</h1>

<table>
  <thead>
    <tr>
      <th>Theme</th>
      <th>Title</th>
      <th>Artist</th>
      <th>Year</th>
      <th>Spotify url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.Theme %></td>
        <td><%= music.Title %></td>
        <td><%= music.Artist %></td>
        <td><%= music.Year %></td>
        <td><%= music.Spotify_url %></td>
        <td><%= link_to 'Show', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/select.html.erb
<div class="whiteback">
<h1><%= @status %></h1>
</div>
<div class="therest companylist">
<table width="100%">
  <thead style="text-align: left; padding-left: 0px;">
    <tr>
      <th width="33%">Title</th>
      <th width="33%">Theme</th>
      <th width="33%">Artist</th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= link_to music.Title, music %></td>
        <td><%= music.Theme %></td>
        <td><%= music.Artist %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/musics/show.html.erb
<?xml version="1.0" encoding = "UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0
Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-
transitional.dtd">
<html xmlns = "http://www.w3.org/1999/xhtml">


<p id="notice"><%= notice %></p>

<head>
<link rel="stylesheet" type="text/css" src="http:// ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css">
<script type"text/Javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"> </script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script>
$(document).ready(function(){
 $("#button").click(function(){
  $.ajax({
      url:"http://lyrics.wikia.com/api.php?func=getSong&artist=Bob_Marley&song=Small_Axe&fmt=realjson&callback=?",
      data: 'get',
      dataType: 'jsonp',
      success: function(data) {
          $("#lyrics").html("<h1>"+data.artist+"</h1>"+"<p>"+data.lyrics+"</p>");
      }
    });
  });
}); 
</script>
</head>

<body>

<div class="compdetail grid_4">
<div class="whiteback">
<h1>
  <%= @music.Title %>
</h1>
</div>
<div class="therest">

<p>
  <strong>Theme:</strong>
  <%= @music.Theme %>
</p>


<p>
  <strong>Artist:</strong>
  <%= @music.Artist %>
</p>

<p>
  <strong>Year:</strong>
  <%= @music.Year %>
</p>

<p>
  <strong><a href="<%= @music.Spotify_url %>"> Spotify link </a></strong>
</p>

<p>
<button id="button">Lyrics</button>
</p>
<div id="lyrics">sss</div>

<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>

app/views/static_pages/contactus.html.erb
<% provide(:title, 'Contact us') %>
<h1>Contact us</h1>
<p>If you liked the app, get in touch!</p>

app/views/static_pages/index.html.erb
<% provide(:title, 'Home') %>
<script>
  function loadXMLDoc()
  {
  var xmlhttp;
  if (window.XMLHttpRequest)
    {// code for IE7+, Firefox, Chrome, Opera, Safari
    xmlhttp=new XMLHttpRequest();
    }
  else
    {// code for IE6, IE5
    xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
  xmlhttp.onreadystatechange=function()
    {
    if (xmlhttp.readyState==4 && xmlhttp.status==200)
      {
      document.getElementById("myDiv").innerHTML=xmlhttp.responseText;
      }
    }
  var str = $( "form" ).serialize();
  xmlhttp.open("GET","select.html?"+str,true);
  xmlhttp.send();
  }
  </script>

  <div class="sidebar grid_4">
  <div class="whiteback"><h1>Listing Songs</h1></div>
  <div class="therest"><form>
    <p><strong>Please select the Theme you want to hear</strong></p>
    <label for="Theme">Theme: </label><br/>
    <!-- <div class="select-style"> -->
    <select id="Theme" name="Theme" onchange="loadXMLDoc()">
      <option value="all">All</option>
      <option value="Love">Love</option>
      <option value="Heartbreak">Heartbreak</option>
      <option value="People and places">People and places</option>
      <option value="Sex">Sex</option>
      <option value="Politics and protest">Politics and protest</option>
      <option value="Life and death">Life and death</option>
      <option value="Party songs">Party songs</option>
    </select><br/>
    </form>
    <button class="button-style" type="button" onclick="loadXMLDoc()">Click me</button>
    </div>
</div>
<div id="myDiv" class="grid_8">
  <div class="whiteback">
  <h1>Welcome!</h1>
  </div>
  <div class="therest">
  <p>In this application you can search for 1000 legendary songs that everyone should listen in their life<br>
   A Spotify url is used for most of the songs. However, some very old songs haven't got the url</p>
  <p>Guest can only view the list while registered users have access to the other details of the songs, Register Now!</p>
  </div>
</div>
<div class="about grid_4">
  <div class="therest">
    <div class="fb-like" data-href="http://www.abdn.ac.uk" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
    <div class="tweet"><a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-count="none">Tweet</a></div>
    <div class="gplus"><div class="g-plusone" data-size="tall" data-annotation="none"></div></div>
    <script type="text/javascript">
      window.___gcfg = {lang: 'en-GB'};

      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/platform.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <br/>
  </div>
</div>

app/views/static_pages/search.html.erb
<% if @musics.size == 0 %>
  <%= @status %>
<% else %>
<table>
  <thead style="text-align: left;">
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |Music| %>
      <tr>
        <td style="font-size: 11px;"><%= link_to Music.Theme, Music %></td>
<!--         <td><%= finance.sector %></td>
        <td><%= finance.location %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>